name: seahorse-app
region: nyc  
workers:  
  - name: worker  
    environment_slug: python  
    github:  
      repo: jaau2422/discord-bot 
      branch: main  
    instance_count: 1  
    instance_size_slug: basic-xxs 
    run_command: python bot.py 